//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmethod_string_builder_Ajax_call_in_asp.net_and.Controller
{


    public partial class WebForm2
    {
    }
}
